"""Pure domain contracts for the personal QQQ Thermometer."""

from .contracts import (
    DEFAULT_CONTRACT_PATH,
    ContractError,
    StrategyContractRegistry,
    StrategyVersionContract,
    load_contract,
)
from .policy import STRATEGY_VERSION, generate_target_snapshot
from .regime import (
    ACTIVE_STATES,
    ALL_STATES,
    REGIME_IMPLEMENTATION_VERSION,
    RegimeConfig,
    RegimeError,
    RegimeEvidence,
    RegimeInput,
    RegimeRun,
    RegimeSnapshot,
    RegimeState,
    evaluate_regime,
    replay_regimes,
)
from .explanation import (
    CLOSE_CONFIRMED,
    CONFIDENCE_CONFIRMED,
    CONFIDENCE_PROVISIONAL,
    CONFIDENCE_UNAVAILABLE,
    DirectionalSignal,
    EXPLANATION_IMPLEMENTATION_VERSION,
    EXPLANATION_SCHEMA,
    ExplanationError,
    ExplanationEvidence,
    ExplanationInput,
    ExplanationModel,
    INTRADAY_PROVISIONAL,
    PUBLICATION_CONFIRMED,
    PUBLICATION_NEEDS_REVIEW,
    PUBLICATION_PROVISIONAL,
    build_explanation,
)

__all__ = [
    "DEFAULT_CONTRACT_PATH",
    "ContractError",
    "StrategyContractRegistry",
    "StrategyVersionContract",
    "load_contract",
    "STRATEGY_VERSION",
    "generate_target_snapshot",
    "ACTIVE_STATES",
    "ALL_STATES",
    "REGIME_IMPLEMENTATION_VERSION",
    "RegimeConfig",
    "RegimeError",
    "RegimeEvidence",
    "RegimeInput",
    "RegimeRun",
    "RegimeSnapshot",
    "RegimeState",
    "evaluate_regime",
    "replay_regimes",
    "CLOSE_CONFIRMED",
    "CONFIDENCE_CONFIRMED",
    "CONFIDENCE_PROVISIONAL",
    "CONFIDENCE_UNAVAILABLE",
    "DirectionalSignal",
    "EXPLANATION_IMPLEMENTATION_VERSION",
    "EXPLANATION_SCHEMA",
    "ExplanationError",
    "ExplanationEvidence",
    "ExplanationInput",
    "ExplanationModel",
    "INTRADAY_PROVISIONAL",
    "PUBLICATION_CONFIRMED",
    "PUBLICATION_NEEDS_REVIEW",
    "PUBLICATION_PROVISIONAL",
    "build_explanation",
]
